apiVersion: v1
kind: ConfigMap
metadata:
  name: yelp-config
  namespace: yelp
data:
  MONGO_URI: "mongodb://mongo:27017"
  MONGO_DB: "yelp_db"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ALLOWED_ORIGINS: '["http://localhost","http://localhost:8080"]'
---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-secrets
  namespace: yelp
type: Opaque
stringData:
  SECRET_KEY: "change-me-in-prod"
