apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-worker
  namespace: yelp
spec:
  replicas: 1
  selector:
    matchLabels: { app: review-worker }
  template:
    metadata:
      labels: { app: review-worker }
    spec:
      containers:
        - name: review-worker
          image: yelp/review-worker:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: { name: yelp-config }
            - secretRef: { name: yelp-secrets }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-worker
  namespace: yelp
spec:
  replicas: 1
  selector:
    matchLabels: { app: restaurant-worker }
  template:
    metadata:
      labels: { app: restaurant-worker }
    spec:
      containers:
        - name: restaurant-worker
          image: yelp/restaurant-worker:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: { name: yelp-config }
            - secretRef: { name: yelp-secrets }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-worker
  namespace: yelp
spec:
  replicas: 1
  selector:
    matchLabels: { app: user-worker }
  template:
    metadata:
      labels: { app: user-worker }
    spec:
      containers:
        - name: user-worker
          image: yelp/user-worker:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: { name: yelp-config }
            - secretRef: { name: yelp-secrets }
